# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_courses', '0002_auto_20170321_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
