# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_courses', '0005_auto_20170322_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='danceClass',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dance_courses.Dance_Class'),
            preserve_default=False,
        ),
    ]
