# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_courses', '0006_post_danceclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='danceClass',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='danceClass',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dance_courses.Dance_Class'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
